server:
  port: 8761

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka8761.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示不去检索服务
    fetchRegistry: false
    serviceUrl:
      #设置注册和查询的地址 Eureka 地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群配置其它Eureka Server即可
      defaultZone: http://eureka8761.com:8761/eureka/
       #,http://eureka8762.com:8762/eureka/


spring:
  application:
    name: eureka-server       #项目名称