spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/martinchen911/spring-cloud-samples.git
          searchPaths: config
          username:   #\u516C\u5F00\u5E93\u4E0D\u7528\u5199\u5BC6\u7801\u8D26\u53F7
          password:
server:
  port: 8888


